name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set Node.js version to your preference

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Build the app
      - name: Build the React app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      # Checkout code again
      - name: Checkout code
        uses: actions/checkout@v2

      # Install sshpass to use password authentication
      - name: Install sshpass
        run: sudo apt-get install sshpass

      # Deploy to DigitalOcean Droplet using password authentication
      - name: Deploy to DigitalOcean Droplet
        run: |
          sshpass -p "${{ secrets.DROPLET_PASSWORD }}" scp -r ./build/* root@164.90.144.250:/../var/www/smart-study-frontend
          sshpass -p "${{ secrets.DROPLET_PASSWORD }}" ssh root@164.90.144.250 << 'EOF'
            # Navigate to the app directory
            cd /../var/www/smart-study-frontend

            npm run build

            # Stop the current PM2 process
            pm2 stop smart-study-frontend
            pm2 delete smart-study-frontend

            # Start the app with PM2
            pm2 start npm --name "smart-study-frontend" -- start

            # Save PM2 process list
            pm2 save
          EOF
        env:
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}

  # Optional: Clean-up or run any additional tasks
